[build]
  command = "npm run build"
  publish = "build"

# Redirect rule for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variable configuration
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "production"
